# Generated by Django 6.0.2 on 2026-02-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="allotment_details",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="cheque_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="cheque_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="cid_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="contact_mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="final_payment_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="passenger_manifest",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_mode",
            field=models.CharField(
                choices=[("Cash", "Cash"), ("Cheque", "Cheque"), ("Online", "Online")],
                default="Cash",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_stage",
            field=models.CharField(
                choices=[
                    ("Advance", "Advance"),
                    ("Part", "Part Payment"),
                    ("Full", "Full Payment"),
                    ("Final", "Final Payment"),
                ],
                default="Advance",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="phone_office",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="phone_residence",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="receipt_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Paid", "Paid")],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="tour_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
